--- #YAML:1.0
name:                Test-Mimic-Generator
version:             0.009005
abstract:            Perl module for generating mock perl packages from data recorded by Test::Mimic::Recorder.
license:             ~
author:              
    - Brendan Roof <broof@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cwd:                           0
    Data::Dumper:                  0
    File::Copy:                    0
    Test::Mimic::Library:          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
